---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
AllCops:
  Exclude:
  - sub/**/*
Style/ExplicitBlockArgument:
  Exclude:
  - lib/ehbrs/videos/unsupported/check_support.rb
Style/FetchEnvVar:
  Exclude:
  - lib/ehbrs/user_dirs.rb
Style/OpenStructUse:
  Exclude:
  - lib/ehbrs/observers/base.rb
  - lib/ehbrs/observers/with_persistence.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - ehbrs-tools.gemspec
  - exe/ehbrs
  - spec/code/rubocop_spec.rb
  - spec/lib/ehbrs/observers/base_spec.rb
  - spec/lib/ehbrs/tools/runner/fs/used_space_spec.rb
  - spec/lib/ehbrs/tools/runner/vg/ips_spec.rb
  - spec/lib/ehbrs/tools/runner/videos/probe_spec.rb
  - spec/lib/ehbrs/tools/runner/videos/unsupported_spec.rb
  - spec/lib/ehbrs/tools/runner_spec.rb
  - spec/spec_helper/videos.rb
  - spec/spec_helper.rb
Style/RedundantRegexpEscape:
  Exclude:
  - lib/ehbrs/videos/file.rb
Style/RedundantReturn:
  Exclude:
  - lib/ehbrs/observers/base.rb
Style/StringConcatenation:
  Exclude:
  - lib/ehbrs/tools/runner/google/translate.rb
  - lib/ehbrs/tools/runner/web_utils/videos/upload.rb
  - lib/ehbrs/videos/convert_job.rb
  - lib/ehbrs/videos/track.rb
  - lib/ehbrs/videos/unsupported/check_support.rb
