---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
AllCops:
  Exclude:
  - sub/**/*
Style/StringConcatenation:
  Exclude:
  - lib/ehbrs/tools/runner/google/translate.rb
  - lib/ehbrs/tools/runner/web_utils/videos/upload.rb
  - lib/ehbrs/videos/convert_job.rb
  - lib/ehbrs/videos/track.rb
  - lib/ehbrs/videos/unsupported/check_support.rb
